# Generated by Django 6.0.1 on 2026-02-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='data',
            new_name='date',
        ),
    ]
