# Generated by Django 6.0.1 on 2026-02-05 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0002_rename_data_patientdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
